# Trong numpy, dùng mảng numpy hai chiều để biểu diễn một ma trận. Mảng hai chiều có thể coi là mảng của các mảng một chiều, trong đó mỗi phần tử là một hàng của ma trận

In [0]:
import numpy as np

In [0]:
a = np.array([[1, 2],
              [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [0]:
len(a)

2

# Ma trận đơn vị

In [0]:
x = np.eye(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
x = np.eye(4, k = 0)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
x = np.eye(4, k = 1)
x

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [0]:
x = np.eye(4, k = -1)
x

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# Ma trận đường chéo

In [0]:
x = np.diag([1, 3, 6, 9])
x

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 9]])

In [0]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
x

In [0]:
np.diag(x, k = 1)

array([2, 6])

In [0]:
x = np.eye(15, k = -1)
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [0]:
np.diag(np.arange(1, 16, 1), k = 1)

array([[ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

# Truy cập từng phần tử của ma trận

In [0]:
A = np.array([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [0]:
A[1]

array([5, 6, 7, 8])

In [0]:
A[1][:]

array([5, 6, 7, 8])

In [0]:
A[1, :]

array([5, 6, 7, 8])

In [0]:
# trả về hàng có chỉ số 1, chứ không phải cột có chỉ số 1
A[:, 1]

array([ 2,  6, 10])

In [0]:
A[:, 2]

# Truy cập nhiều phần tử của ma trận

## nhiều phần tử trên một hàng

In [0]:
A = np.array([
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [0]:
A[0, 2:]

array([3, 4])

In [0]:
A[1, range(0, A.shape[1], 2)]

array([5, 7])

## nhiều phần tử trên một cột

In [0]:
A[[0, 2], -1]

array([ 4, 12])

## nhiều hàng, nhiều cột

In [0]:
A[[1, 2]][:, [0, 3]]

array([[ 5,  8],
       [ 9, 12]])

## cặp các tọa độ

In [0]:
# return A[1, 0] A[2, 3]
A[[1, 2], [0, 3]]

array([ 5, 12])

# np.sum, np.min, np.max, np.mean

In [0]:
A = np.array([[1., 2, 3, 2], [4, 3, 7, 4], [1, 4, 2, 3]])
A

array([[1., 2., 3., 2.],
       [4., 3., 7., 4.],
       [1., 4., 2., 3.]])

In [0]:
np.sum(A, axis = 0)

array([ 6.,  9., 12.,  9.])

In [0]:
np.min(A, axis = 0)

array([1., 2., 2., 2.])

In [0]:
np.max(A, axis = 0)

array([4., 4., 7., 4.])

In [0]:
np.mean(A, axis = 0)

array([2., 3., 4., 3.])

In [0]:
np.sum(A, axis = 1)

array([ 8., 18., 10.])

In [0]:
np.min(A, axis = 1)

array([1., 3., 1.])

In [0]:
np.max(A, axis = 1)

array([3., 7., 4.])

In [0]:
np.mean(A, axis = 1)

array([2. , 4.5, 2.5])

In [0]:
# khi không có axis sẽ tính trên toàn bộ ma trận
np.sum(A)

36.0

In [0]:
np.min(A)

1.0

In [0]:
np.max(A)

7.0

In [0]:
np.mean(A)

3.0

## keepdims = True
##### Đôi khi, để thuận tiện cho việc tính toán về sau, chúng ta muốn kết quả trả về khi axis = 0 là các vector hàng thực sự, khi axis = 1 là các vector cột thực sự. Để làm được việc đó, Numpy cung cấp thuộc tính keepdims = True (mặc định là False). Khi keepdims = True, nếu sử dụng axis = 0, kết quả sẽ là một mảng hai chiều có chiều thứ nhất bằng 1 (coi như ma trận một hàng). Tương tự, nếu sử dụng axis = 1, kết quả sẽ là một mảng hai chiều có chiều thứ hai bằng 1 (một ma trận có số cột bằng 1). Việc này, về sau chúng ta sẽ thấy, quan trọng trong nhiều trường hợp đặc biệt:

In [0]:
A

array([[1., 2., 3., 2.],
       [4., 3., 7., 4.],
       [1., 4., 2., 3.]])

In [0]:
x = np.sum(A, axis = 0, keepdims=True)

In [0]:
x.shape

(1, 4)

# Phép toán tác động lên mọi phần tử của ma trận - Frobenius norm

In [0]:
frobenius_norm = np.sqrt(np.sum(A**2))
frobenius_norm

11.74734012447073

# Reshape

In [0]:
A

array([[1., 2., 3., 2.],
       [4., 3., 7., 4.],
       [1., 4., 2., 3.]])

In [0]:
# flaten
A.reshape(12)

array([1., 2., 3., 2., 4., 3., 7., 4., 1., 4., 2., 3.])

In [0]:
A.reshape(-1)

array([1., 2., 3., 2., 4., 3., 7., 4., 1., 4., 2., 3.])

In [0]:
A.reshape(6, -1)

array([[1., 2.],
       [3., 2.],
       [4., 3.],
       [7., 4.],
       [1., 4.],
       [2., 3.]])

In [0]:
A.reshape(12, -1)

array([[1.],
       [2.],
       [3.],
       [2.],
       [4.],
       [3.],
       [7.],
       [4.],
       [1.],
       [4.],
       [2.],
       [3.]])

In [0]:
A.reshape(2, 3, -1)

array([[[1., 2.],
        [3., 2.],
        [4., 3.]],

       [[7., 4.],
        [1., 4.],
        [2., 3.]]])

# Thứ tự của phép toán reshape

## C-order - default

## F-order

In [0]:
A.reshape(3, 4, order='F')


array([[1., 2., 3., 2.],
       [4., 3., 7., 4.],
       [1., 4., 2., 3.]])

In [0]:
import numpy as np 

def fullSoftmax(Z):
    """ a vectorization implementation of softmax
    input: Z: a n-by-d np array, each row is one score vector
    output: A: a n-by-d np array, each row is the softmax of 
    one row of z
    """
    ## TODO ## 
    max = np.max(Z, axis=1, keepdims=True)
    print(max.shape)
    y = Z - max
    return np.exp(y)/np.sum(np.exp(y), axis = 1, keepdims=True)
    
    ## end TODO ##
    return A 


In [5]:
np.random.seed(10) # for the same output 
Z = np.random.randn(10000, 100)*1000 # 10000 points, 100 class  

print(Z.shape)

A = fullSoftmax(Z)
print("{:.2f}".format(np.sum(A**2)))

(10000, 100)
(10000, 1)
9971.15


In [6]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
B = np.array([[2],
              [2],
              [2]])
B

array([[2],
       [2],
       [2]])

In [12]:
A / B

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])