In [0]:
import numpy as np

# Numpy không quy ước vector là vector hàng hay cột, mà chỉ coi nó là mảng một chiều, nếu muốn có một vector cột, phải coi nó là một ma trận có chiều thứ 2 bằng 1

In [0]:
help(np.array)

In [3]:
x = [1, 2, 3, 4, 5, 6]
a = np.array(x)
a

array([1, 2, 3, 4, 5, 6])

In [4]:
print(type(a[0]))

<class 'numpy.int64'>


# Vector 0

In [5]:
zero = np.zeros(4)
zero

array([0., 0., 0., 0.])

In [6]:
one = np.ones(4)
one

array([1., 1., 1., 1.])

In [7]:
x = np.array([1, 2, 3, 4])
zero_like = np.zeros_like(x)
zero_like

array([0, 0, 0, 0])

In [8]:
one_like = np.ones_like(x)
one_like

array([1, 1, 1, 1])

# Cấp số cộng

In [9]:
# Để tạo mảng số nguyên từ 0 -> (n-1) [n số tổng cộng] ta dùng hàm np.arange(n)
a = np.arange(3)
a

array([0, 1, 2])

In [10]:
# Tạo mảng các số nguyên từ m -> (n-1)
a = np.arange(3, 6)
a

array([3, 4, 5])

In [11]:
# tạo một cấp số cộng với phần tử đầu là a, công sai d dương, phần tử cuối là số lớn nhất nhỏ hơn b
a = 3
b = 10
d = 2
x = np.arange(a, b, d)
x

array([3, 5, 7, 9])

In [12]:
# Nếu d là 1 số âm và b < a thì phần tử cuối là phần tử nhỏ nhất của cấp số cộng lớn hơn b
x = np.arange(5, 1, -1)
x

array([5, 4, 3, 2])

In [13]:
a = np.arange(0, 11) # 0->10
x = 2**a
x

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])

In [14]:
a = np.arange(10, dtype=float)
a[0:9] = 3
a[-1] = 1.5
a

array([3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 1.5])

# Truy cập nhiều phần tử của mảng

## Đọc

In [23]:
a = 2*np.arange(10)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
ids = [1, 3, 5, 7]
a[ids]

array([ 2,  6, 10, 14])

In [25]:
ids = np.arange(1, 7, 2)
a[ids]

array([ 2,  6, 10])

In [26]:
a[:3]

array([0, 2, 4])

In [27]:
a[-3:]

array([14, 16, 18])

In [28]:
a[1:4]

array([2, 4, 6])

## Ghi

In [29]:
ids = [1, 3, 5]
a[ids] = 1
a

array([ 0,  1,  4,  1,  8,  1, 12, 14, 16, 18])

In [30]:
a[-3:] = np.array([0, -10, -20])
a

array([  0,   1,   4,   1,   8,   1,  12,   0, -10, -20])

In [31]:
# return all elements with even indexes
a[::2]

array([  0,   4,   8,  12, -10])

In [32]:
# reverse an array
a[::-1]

array([-20, -10,   0,  12,   1,   8,   1,   4,   1,   0])

more
https://www.tutorialspoint.com/numpy/numpy_indexing_and_slicing.htm

# Tính toán giữa các mảng một chiều và số vô hướng

## phép toán giữa mảng một chiều với một số vô hướng

In [54]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [55]:
x + 3

array([4, 5, 6])

In [56]:
6/x

array([6., 3., 2.])

In [57]:
3**x

array([ 3,  9, 27])

## phép toán giữa hai mảng một chiều

In [0]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [59]:
x + y

array([5, 7, 9])

In [60]:
x - y

array([-3, -3, -3])

In [61]:
x*y

array([ 4, 10, 18])

In [62]:
x/y

array([0.25, 0.4 , 0.5 ])

In [63]:
x**y

array([  1,  32, 729])

## các hàm toán học

In [64]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [66]:
# e^x
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [67]:
np.sum(x)

6

# NORM 1

## norm 1 của vector là tổng giá trị tuyệt đối của các phần tử

In [0]:
x = np.random.randn(1000)
x

In [70]:
norm1 = np.sum(np.abs(x))
norm1

813.1313112009864

# Hàm Softmax cho mảng một chiều

In [71]:
x = np.random.randn(10)
x

array([-0.83853903,  0.76864389, -1.47493364,  1.6182072 , -1.48618259,
       -0.4377863 ,  0.04069277,  0.72148396,  0.330704  , -0.07196706])

In [72]:
softmax = np.exp(x)/np.sum(np.exp(x))
softmax

array([0.03054288, 0.15237041, 0.0161632 , 0.35633729, 0.0159824 ,
       0.04559893, 0.07357927, 0.14535144, 0.09833446, 0.06573973])

# Tích vô hướng(inner product) của 2 vector - Norm 2

In [0]:
x = np.arange(3)
y = np.ones(3)

In [75]:
inner_product = np.sum(x*y)
inner_product

3.0

In [0]:
inner_product = np.dot(x, y)
inner_product = x.dot(y)

In [77]:
norm2 = np.linalg.norm(x)
norm2

2.23606797749979

# min, max, argmin, argmax của mảng một chiều

## để tìm GTLN, GTNN của mảng một chiều ta sử dụng np.min hoạc np.max

In [0]:
a = np.random.randn(20)

In [79]:
np.min(a)

-1.0415224459573664

In [80]:
np.max(a)

1.8867548476869125

## để tìm chỉ số mà tại đó mảng một chiều đạt min hoạc max ta dùng np.argmin hoạc np.argmax

In [81]:
np.argmin(a)

17

In [82]:
np.argmax(a)

4

# Softmax II - Phiên bản ổn định

In [0]:
x = np.random.randn(20)

In [84]:
stable_softmax = np.exp(x - np.max(x))/np.exp(np.sum(x - np.max(x)))
stable_softmax

array([3.19650672e+19, 7.67620833e+18, 1.64606528e+20, 3.03725684e+19,
       1.34571372e+19, 8.75541711e+19, 2.14229630e+19, 2.25557926e+20,
       1.81913432e+20, 1.05940231e+20, 2.27472055e+19, 9.78514723e+18,
       5.44427820e+19, 3.55064438e+19, 1.01183880e+20, 2.25258632e+19,
       2.15025003e+20, 8.88115914e+19, 3.81859386e+19, 5.98215778e+20])